name: Deploy to Firebase

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web-app/package-lock.json

    - name: Install web app dependencies
      run: |
        cd web-app
        npm ci

    - name: Install functions dependencies
      run: |
        cd functions
        npm ci

    - name: Build web app for production
      run: |
        cd web-app
        npm run build:prod

    - name: Build functions
      run: |
        cd functions
        npm run build

    - name: Deploy to Firebase
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json
        npx firebase-tools@13.20.2 deploy --only hosting,functions,firestore,dataconnect --project nakevlink --force --json
      env:
        FIREBASE_CLI_PREVIEWS: 'hostingchannels'